# Generated by Django 3.0.8 on 2020-08-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuserr', models.CharField(max_length=1000)),
                ('owner', models.CharField(max_length=1000)),
                ('masseage', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500)),
                ('fuser', models.CharField(max_length=1000)),
            ],
        ),
    ]
