# Generated by Django 3.0.8 on 2020-08-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0002_data_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500)),
                ('croom', models.CharField(max_length=10000)),
            ],
        ),
    ]
